Tipo_di_veicolo= "Tipo di veicolo"n;
drop "Tipo di veicolo"n;
Posti_a_sedere= "Posti a sedere"n;
drop "Posti a sedere"n;
Tipo_di_cambio= "Tipo di cambio"n;
drop "Tipo di cambio"n;
Tipo_di_unita= "Tipo di unita"n;
drop "Tipo di unita"n;
Colore_esterno= "Colore esterno"n;
drop "Colore esterno"n;
Emissioni_di_CO2= "Emissioni di CO2"n;
drop "Emissioni di CO2"n;
Colore_originale= "Colore originale"n;
drop "Colore originale"n;
Tipo_di_vernice= "Tipo di vernice"n;
drop "Tipo di vernice"n;
Peso_a_vuoto= "Peso a vuoto"n;
drop "Peso a vuoto"n;
Usato_Garantito= "Usato Garantito"n;
drop "Usato Garantito"n;
Per_neopatentati= "Per neopatentati"n;
drop "Per neopatentati"n;
Classe_emissioni= "Classe emissioni"n;
drop "Classe emissioni"n;
Veicolo_per_non_fumatori= "Veicolo per non fumatori"n;
drop "Veicolo per non fumatori"n;
Consumo_carburante_combinato= "Consumo carburante combinato"n;
drop "Consumo carburante combinato"n;
Consumo_carburante_urbano= "Consumo carburante urbano"n;
drop "Consumo carburante urbano"n;
Consumo_carburante_extraurb= "Consumo carburante extraurb"n;
drop "Consumo carburante extraurb"n;
Tagliandi_certificati= "Tagliandi certificati"n;
drop "Tagliandi certificati"n;
