*;
* IMPUTE VARIABLE: Classe_emissioni;
*;
length IMP_Classe_emissioni $12;
label IMP_Classe_emissioni = 'Imputed Classe_emissioni';
IMP_Classe_emissioni = Classe_emissioni;
if IMP_Classe_emissioni eq '' then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH I_Classe_emissioni $ 12;
LENGTH U_Classe_emissioni $ 12;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_Classe_emissioniElettrica = 'Previsto: Classe_emissioni=Elettrica';
label P_Classe_emissioniEuro_6c = 'Previsto: Classe_emissioni=Euro 6c';
label P_Classe_emissioniEuro_6 = 'Previsto: Classe_emissioni=Euro 6';
label P_Classe_emissioniEuro_6d_TEMP =
'Previsto: Classe_emissioni=Euro 6d-TEMP';
label P_Classe_emissioniEuro_6d = 'Previsto: Classe_emissioni=Euro 6d';
label P_Classe_emissioniEuro_4 = 'Previsto: Classe_emissioni=Euro 4';
label P_Classe_emissioniEuro_5 = 'Previsto: Classe_emissioni=Euro 5';
label Q_Classe_emissioniElettrica =
'P non corretto: Classe_emissioni=Elettrica';
label Q_Classe_emissioniEuro_6c = 'P non corretto: Classe_emissioni=Euro 6c';
label Q_Classe_emissioniEuro_6 = 'P non corretto: Classe_emissioni=Euro 6';
label Q_Classe_emissioniEuro_6d_TEMP =
'P non corretto: Classe_emissioni=Euro 6d-TEMP';
label Q_Classe_emissioniEuro_6d = 'P non corretto: Classe_emissioni=Euro 6d';
label Q_Classe_emissioniEuro_4 = 'P non corretto: Classe_emissioni=Euro 4';
label Q_Classe_emissioniEuro_5 = 'P non corretto: Classe_emissioni=Euro 5';
label I_Classe_emissioni = 'In: Classe_emissioni';
label U_Classe_emissioni = 'Non normalizzata in: Classe_emissioni';
label _WARN_ = 'Avvertimenti';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_23 $ 23;
DROP _ARBFMT_23;
_ARBFMT_23 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_17 $ 17;
DROP _ARBFMT_17;
_ARBFMT_17 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_10 $ 10;
DROP _ARBFMT_10;
_ARBFMT_10 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Cilindri , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('3' ,'4' ,'1' ,'2' ,'6' ,'8' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Alimentazione ) THEN DO;
_ARBFMT_17 = PUT( Alimentazione , $17.);
%DMNORMIP( _ARBFMT_17);
IF _ARBFMT_17 IN ('BENZINA' ,'DIESEL' ,'ELETTRICA/BENZINA' ,'METANO' ,
'GPL' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_17 IN ('ELETTRICA' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF 1 <= REP_Cilindrata THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_Cilindrata < 1 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_Classe_emissioniElettrica = 0.93333333333333;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.05;
P_Classe_emissioniEuro_6d_TEMP = 0.01666666666666;
P_Classe_emissioniEuro_6d = 0;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0.93333333333333;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.05;
Q_Classe_emissioniEuro_6d_TEMP = 0.01666666666666;
Q_Classe_emissioniEuro_6d = 0;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'ELETTRICA';
U_Classe_emissioni = 'Elettrica';
END;
ELSE DO;
_ARBFMT_17 = PUT( Alimentazione , $17.);
%DMNORMIP( _ARBFMT_17);
IF _ARBFMT_17 IN ('ELETTRICA' ) THEN DO;
P_Classe_emissioniElettrica = 0.2;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0;
P_Classe_emissioniEuro_6d_TEMP = 0.6;
P_Classe_emissioniEuro_6d = 0.2;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0.2;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0;
Q_Classe_emissioniEuro_6d_TEMP = 0.6;
Q_Classe_emissioniEuro_6d = 0.2;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6D-TEMP';
U_Classe_emissioni = 'Euro 6d-TEMP';
END;
ELSE DO;
IF NOT MISSING(REP_Peso_a_vuoto ) AND
937.5 <= REP_Peso_a_vuoto THEN DO;
IF NOT MISSING(REP_Anno ) AND
REP_Anno < 2017.5 THEN DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.66666666666666;
P_Classe_emissioniEuro_6d_TEMP = 0.22222222222222;
P_Classe_emissioniEuro_6d = 0;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0.11111111111111;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.66666666666666;
Q_Classe_emissioniEuro_6d_TEMP = 0.22222222222222;
Q_Classe_emissioniEuro_6d = 0;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0.11111111111111;
I_Classe_emissioni = 'EURO 6';
U_Classe_emissioni = 'Euro 6';
END;
ELSE DO;
_ARBFMT_23 = PUT( Carrozzeria , $23.);
%DMNORMIP( _ARBFMT_23);
IF _ARBFMT_23 IN ('ALTRO' ) THEN DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Porte , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('5' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('3' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF REP_Cilindrata < 2239 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 2239 <= REP_Cilindrata THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF 14545 <= REP_price THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_price < 14545 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.04135338345864;
P_Classe_emissioniEuro_6d_TEMP = 0.94360902255639;
P_Classe_emissioniEuro_6d = 0.01503759398496;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.04135338345864;
Q_Classe_emissioniEuro_6d_TEMP = 0.94360902255639;
Q_Classe_emissioniEuro_6d = 0.01503759398496;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6D-TEMP';
U_Classe_emissioni = 'Euro 6d-TEMP';
END;
ELSE DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.8;
P_Classe_emissioniEuro_6d_TEMP = 0.2;
P_Classe_emissioniEuro_6d = 0;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.8;
Q_Classe_emissioniEuro_6d_TEMP = 0.2;
Q_Classe_emissioniEuro_6d = 0;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6';
U_Classe_emissioni = 'Euro 6';
END;
END;
ELSE DO;
_ARBFMT_10 = PUT( Tipo_di_unita , $10.);
%DMNORMIP( _ARBFMT_10);
IF _ARBFMT_10 IN ('POSTERIORE' ,'ANTERIORE' ,'4X4' ) THEN DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.56583455702398;
P_Classe_emissioniEuro_6d_TEMP = 0.38325991189427;
P_Classe_emissioniEuro_6d = 0.05090553108174;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.56583455702398;
Q_Classe_emissioniEuro_6d_TEMP = 0.38325991189427;
Q_Classe_emissioniEuro_6d = 0.05090553108174;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6';
U_Classe_emissioni = 'Euro 6';
END;
ELSE DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.10828025477707;
P_Classe_emissioniEuro_6d_TEMP = 0.87261146496815;
P_Classe_emissioniEuro_6d = 0.01910828025477;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.10828025477707;
Q_Classe_emissioniEuro_6d_TEMP = 0.87261146496815;
Q_Classe_emissioniEuro_6d = 0.01910828025477;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6D-TEMP';
U_Classe_emissioni = 'Euro 6d-TEMP';
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Usato_Garantito , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Carrozzeria ) THEN DO;
_ARBFMT_23 = PUT( Carrozzeria , $23.);
%DMNORMIP( _ARBFMT_23);
IF _ARBFMT_23 IN ('BERLINA' ,'CABRIO' ,'ALTRO' ,
'SUV/FUORISTRADA/PICK-UP' ,'STATION WAGON' ,'MONOVOLUME' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_23 IN ('CITY CAR' ,'434F5550C383C2A9'x ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Tagliandi_certificati ) THEN DO;
_ARBFMT_12 = PUT( Tagliandi_certificati , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
IF NOT MISSING(REP_Consumo_Carburante_Totale ) AND
3.65 <= REP_Consumo_Carburante_Totale THEN DO;
IF NOT MISSING(REP_Emissioni_di_CO2 ) AND
REP_Emissioni_di_CO2 < 82.5 THEN DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0;
P_Classe_emissioniEuro_6d_TEMP = 1;
P_Classe_emissioniEuro_6d = 0;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0;
Q_Classe_emissioniEuro_6d_TEMP = 1;
Q_Classe_emissioniEuro_6d = 0;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6D-TEMP';
U_Classe_emissioni = 'Euro 6d-TEMP';
END;
ELSE DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0.01016949152542;
P_Classe_emissioniEuro_6 = 0.87118644067796;
P_Classe_emissioniEuro_6d_TEMP = 0.10847457627118;
P_Classe_emissioniEuro_6d = 0.01016949152542;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0.01016949152542;
Q_Classe_emissioniEuro_6 = 0.87118644067796;
Q_Classe_emissioniEuro_6d_TEMP = 0.10847457627118;
Q_Classe_emissioniEuro_6d = 0.01016949152542;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6';
U_Classe_emissioni = 'Euro 6';
END;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Posti_a_sedere , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('5' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('4' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Porte ) THEN DO;
_ARBFMT_12 = PUT( Porte , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('5' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('3' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF 14350 <= REP_price THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_price < 14350 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.4;
P_Classe_emissioniEuro_6d_TEMP = 0.1;
P_Classe_emissioniEuro_6d = 0.45;
P_Classe_emissioniEuro_4 = 0.05;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.4;
Q_Classe_emissioniEuro_6d_TEMP = 0.1;
Q_Classe_emissioniEuro_6d = 0.45;
Q_Classe_emissioniEuro_4 = 0.05;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6D';
U_Classe_emissioni = 'Euro 6d';
END;
ELSE DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.37777777777777;
P_Classe_emissioniEuro_6d_TEMP = 0.61111111111111;
P_Classe_emissioniEuro_6d = 0;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0.01111111111111;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.37777777777777;
Q_Classe_emissioniEuro_6d_TEMP = 0.61111111111111;
Q_Classe_emissioniEuro_6d = 0;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0.01111111111111;
I_Classe_emissioni = 'EURO 6D-TEMP';
U_Classe_emissioni = 'Euro 6d-TEMP';
END;
END;
END;
ELSE DO;
P_Classe_emissioniElettrica = 0;
P_Classe_emissioniEuro_6c = 0;
P_Classe_emissioniEuro_6 = 0.98409893992932;
P_Classe_emissioniEuro_6d_TEMP = 0.01236749116607;
P_Classe_emissioniEuro_6d = 0.00353356890459;
P_Classe_emissioniEuro_4 = 0;
P_Classe_emissioniEuro_5 = 0;
Q_Classe_emissioniElettrica = 0;
Q_Classe_emissioniEuro_6c = 0;
Q_Classe_emissioniEuro_6 = 0.98409893992932;
Q_Classe_emissioniEuro_6d_TEMP = 0.01236749116607;
Q_Classe_emissioniEuro_6d = 0.00353356890459;
Q_Classe_emissioniEuro_4 = 0;
Q_Classe_emissioniEuro_5 = 0;
I_Classe_emissioni = 'EURO 6';
U_Classe_emissioni = 'Euro 6';
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: Classe_emissioni;
*;
length _format200 $200;
drop _format200;
_format200 = strip(I_Classe_emissioni);
if _format200="EURO 6D-TEMP" then IMP_Classe_emissioni = "Euro 6d-TEMP";
else
if _format200="EURO 6D" then IMP_Classe_emissioni = "Euro 6d     ";
else
if _format200="EURO 6C" then IMP_Classe_emissioni = "Euro 6c     ";
else
if _format200="EURO 6" then IMP_Classe_emissioni = "Euro 6      ";
else
if _format200="EURO 5" then IMP_Classe_emissioni = "Euro 5      ";
else
if _format200="EURO 4" then IMP_Classe_emissioni = "Euro 4      ";
else
if _format200="ELETTRICA" then IMP_Classe_emissioni = "Elettrica   ";
END;
