*;
* IMPUTE VARIABLE: REP_Tipo_di_vernice;
*;
length IMP_REP_Tipo_di_vernice $12;
label IMP_REP_Tipo_di_vernice = 'Imputed: Replacement: Tipo_di_vernice';
IMP_REP_Tipo_di_vernice = REP_Tipo_di_vernice;
if IMP_REP_Tipo_di_vernice eq '' then do;
****************************************************************;
****** DECISION TREE SCORING CODE ******;
****************************************************************;
****** LENGTHS OF NEW CHARACTER VARIABLES ******;
LENGTH I_REP_Tipo_di_vernice $ 12;
LENGTH U_REP_Tipo_di_vernice $ 12;
LENGTH _WARN_ $ 4;
****** LABELS FOR NEW VARIABLES ******;
label P_REP_Tipo_di_vernicBase = 'Previsto: REP_Tipo_di_vernice=Base';
label P_REP_Tipo_di_vernicMetallizzato =
'Previsto: REP_Tipo_di_vernice=Metallizzato';
label P_REP_Tipo_di_vernicPerlato = 'Previsto: REP_Tipo_di_vernice=Perlato';
label Q_REP_Tipo_di_vernicBase = 'P non corretto: REP_Tipo_di_vernice=Base';
label Q_REP_Tipo_di_vernicMetallizzato =
'P non corretto: REP_Tipo_di_vernice=Metallizzato';
label Q_REP_Tipo_di_vernicPerlato =
'P non corretto: REP_Tipo_di_vernice=Perlato';
label I_REP_Tipo_di_vernice = 'In: REP_Tipo_di_vernice';
label U_REP_Tipo_di_vernice = 'Non normalizzata in: REP_Tipo_di_vernice';
label _WARN_ = 'Avvertimenti';
****** TEMPORARY VARIABLES FOR FORMATTED VALUES ******;
LENGTH _ARBFMT_12 $ 12;
DROP _ARBFMT_12;
_ARBFMT_12 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_11 $ 11;
DROP _ARBFMT_11;
_ARBFMT_11 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_20 $ 20;
DROP _ARBFMT_20;
_ARBFMT_20 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_23 $ 23;
DROP _ARBFMT_23;
_ARBFMT_23 = ' ';
/* Initialize to avoid warning. */
LENGTH _ARBFMT_17 $ 17;
DROP _ARBFMT_17;
_ARBFMT_17 = ' ';
/* Initialize to avoid warning. */
****** ASSIGN OBSERVATION TO NODE ******;
DROP _BRANCH_;
_BRANCH_ = -1;
_ARBFMT_11 = PUT( Colore_esterno , $11.);
%DMNORMIP( _ARBFMT_11);
IF _ARBFMT_11 IN ('NERO' ,'BLU/AZZURRO' ,'GRIGIO' ,'ARGENTO' ,'VERDE' ,
'MARRONE' ,'BEIGE' ,'BRONZO' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_11 IN ('BIANCO' ,'ROSSO' ,'ARANCIONE' ,'GIALLO' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF 7845 <= REP_price THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_price < 7845 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
_ARBFMT_20 = PUT( Modello , $20.);
%DMNORMIP( _ARBFMT_20);
IF _ARBFMT_20 IN ('FORTWO' ,'PARTNER' ,'PANDA' ,'YPSILON' ,'500X' ,
'COMPASS' ,'TIPO' ,'500L' ,'C-HR' ,'COMBO' ,'DOBLO' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_20 IN ('A4' ,'CAPTUR' ,'RENEGADE' ,'GRANDLAND X' ,'CLIO' ,
'VITARA' ,'X1' ,'508' ,'GOLF' ,'A5' ,'A3' ,'POLO' ,'ARONA' ,'QASHQAI' ,
'X-TRAIL' ,'OCTAVIA' ,'420' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF REP_price < 19245 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 19245 <= REP_price THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF REP_Cilindrata < 1370.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1370.5 <= REP_Cilindrata THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
_ARBFMT_20 = PUT( Modello , $20.);
%DMNORMIP( _ARBFMT_20);
IF _ARBFMT_20 IN ('C-HR' ) THEN DO;
P_REP_Tipo_di_vernicBase = 0;
P_REP_Tipo_di_vernicMetallizzato = 0.6;
P_REP_Tipo_di_vernicPerlato = 0.4;
Q_REP_Tipo_di_vernicBase = 0;
Q_REP_Tipo_di_vernicMetallizzato = 0.6;
Q_REP_Tipo_di_vernicPerlato = 0.4;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_11 = PUT( Colore_esterno , $11.);
%DMNORMIP( _ARBFMT_11);
IF _ARBFMT_11 IN ('BIANCO' ,'GIALLO' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_11 IN ('ROSSO' ,'ARANCIONE' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF 8800 <= REP_price THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_price < 8800 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
_BRANCH_ = -1;
_ARBFMT_20 = PUT( Modello , $20.);
%DMNORMIP( _ARBFMT_20);
IF _ARBFMT_20 IN ('PANDA' ,'YPSILON' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_20 IN ('500' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Porte ) THEN DO;
_ARBFMT_12 = PUT( Porte , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('5' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('3' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF REP_price < 11600 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 11600 <= REP_price THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_REP_Tipo_di_vernicBase = 0.55102040816326;
P_REP_Tipo_di_vernicMetallizzato = 0.44897959183673;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.55102040816326;
Q_REP_Tipo_di_vernicMetallizzato = 0.44897959183673;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'BASE';
U_REP_Tipo_di_vernice = 'Base';
END;
ELSE DO;
P_REP_Tipo_di_vernicBase = 0.41509433962264;
P_REP_Tipo_di_vernicMetallizzato = 0.58490566037735;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.41509433962264;
Q_REP_Tipo_di_vernicMetallizzato = 0.58490566037735;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
END;
ELSE DO;
_ARBFMT_12 = PUT( Cilindri , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
P_REP_Tipo_di_vernicBase = 0;
P_REP_Tipo_di_vernicMetallizzato = 1;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0;
Q_REP_Tipo_di_vernicMetallizzato = 1;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_ARBFMT_12 = PUT( Tagliandi_certificati , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
P_REP_Tipo_di_vernicBase = 0.27272727272727;
P_REP_Tipo_di_vernicMetallizzato = 0.72727272727272;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.27272727272727;
Q_REP_Tipo_di_vernicMetallizzato = 0.72727272727272;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
P_REP_Tipo_di_vernicBase = 0.83286908077994;
P_REP_Tipo_di_vernicMetallizzato = 0.16434540389972;
P_REP_Tipo_di_vernicPerlato = 0.00278551532033;
Q_REP_Tipo_di_vernicBase = 0.83286908077994;
Q_REP_Tipo_di_vernicMetallizzato = 0.16434540389972;
Q_REP_Tipo_di_vernicPerlato = 0.00278551532033;
I_REP_Tipo_di_vernice = 'BASE';
U_REP_Tipo_di_vernice = 'Base';
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(REP_Emissioni_di_CO2 ) AND
REP_Emissioni_di_CO2 < 121.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(REP_Emissioni_di_CO2 ) AND
121.5 <= REP_Emissioni_di_CO2 THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Consumo_Carburante_Totale ) THEN DO;
IF REP_Consumo_Carburante_Totale < 5.35 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 5.35 <= REP_Consumo_Carburante_Totale
THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF REP_Cilindrata < 1990 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1990 <= REP_Cilindrata THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_REP_Tipo_di_vernicBase = 0.5040650406504;
P_REP_Tipo_di_vernicMetallizzato = 0.49593495934959;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.5040650406504;
Q_REP_Tipo_di_vernicMetallizzato = 0.49593495934959;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'BASE';
U_REP_Tipo_di_vernice = 'Base';
END;
ELSE DO;
P_REP_Tipo_di_vernicBase = 0.245;
P_REP_Tipo_di_vernicMetallizzato = 0.74;
P_REP_Tipo_di_vernicPerlato = 0.015;
Q_REP_Tipo_di_vernicBase = 0.245;
Q_REP_Tipo_di_vernicMetallizzato = 0.74;
Q_REP_Tipo_di_vernicPerlato = 0.015;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Cilindri , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('2' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ,'3' ,'4' ,'1' ,'6' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF REP_Cilindrata < 886.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 886.5 <= REP_Cilindrata THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
IF NOT MISSING(REP_Cilindrata ) AND
2994 <= REP_Cilindrata THEN DO;
P_REP_Tipo_di_vernicBase = 0.1578947368421;
P_REP_Tipo_di_vernicMetallizzato = 0.73684210526315;
P_REP_Tipo_di_vernicPerlato = 0.10526315789473;
Q_REP_Tipo_di_vernicBase = 0.1578947368421;
Q_REP_Tipo_di_vernicMetallizzato = 0.73684210526315;
Q_REP_Tipo_di_vernicPerlato = 0.10526315789473;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_ARBFMT_23 = PUT( Carrozzeria , $23.);
%DMNORMIP( _ARBFMT_23);
IF _ARBFMT_23 IN ('434F5550C383C2A9'x ) THEN DO;
P_REP_Tipo_di_vernicBase = 0.05263157894736;
P_REP_Tipo_di_vernicMetallizzato = 0.84210526315789;
P_REP_Tipo_di_vernicPerlato = 0.10526315789473;
Q_REP_Tipo_di_vernicBase = 0.05263157894736;
Q_REP_Tipo_di_vernicMetallizzato = 0.84210526315789;
Q_REP_Tipo_di_vernicPerlato = 0.10526315789473;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_ARBFMT_12 = PUT( Cilindri , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('0' ,'3' ,'4' ,'1' ,'6' ) THEN DO;
P_REP_Tipo_di_vernicBase = 0.1147455867082;
P_REP_Tipo_di_vernicMetallizzato = 0.88473520249221;
P_REP_Tipo_di_vernicPerlato = 0.00051921079958;
Q_REP_Tipo_di_vernicBase = 0.1147455867082;
Q_REP_Tipo_di_vernicMetallizzato = 0.88473520249221;
Q_REP_Tipo_di_vernicPerlato = 0.00051921079958;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_BRANCH_ = -1;
IF NOT MISSING(REP_Emissioni_di_CO2 ) AND
REP_Emissioni_di_CO2 < 108.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF NOT MISSING(REP_Emissioni_di_CO2 ) AND
108.5 <= REP_Emissioni_di_CO2 THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_Cilindrata ) THEN DO;
IF REP_Cilindrata < 1120.5 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 1120.5 <= REP_Cilindrata THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF REP_price < 23900 THEN DO;
_BRANCH_ = 1;
END;
ELSE IF 23900 <= REP_price THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_REP_Tipo_di_vernicBase = 0.8125;
P_REP_Tipo_di_vernicMetallizzato = 0.1875;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.8125;
Q_REP_Tipo_di_vernicMetallizzato = 0.1875;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'BASE';
U_REP_Tipo_di_vernice = 'Base';
END;
ELSE DO;
P_REP_Tipo_di_vernicBase = 0.25842696629213;
P_REP_Tipo_di_vernicMetallizzato = 0.74157303370786;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.25842696629213;
Q_REP_Tipo_di_vernicMetallizzato = 0.74157303370786;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
END;
END;
END;
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( Usato_Garantito , BEST12.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('1' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('0' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(REP_price ) THEN DO;
IF 13475 <= REP_price THEN DO;
_BRANCH_ = 1;
END;
ELSE IF REP_price < 13475 THEN DO;
_BRANCH_ = 2;
END;
ELSE _BRANCH_ = 1;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 1;
IF _BRANCH_ EQ 2 THEN DO;
P_REP_Tipo_di_vernicBase = 0.14285714285714;
P_REP_Tipo_di_vernicMetallizzato = 0.85714285714285;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.14285714285714;
Q_REP_Tipo_di_vernicMetallizzato = 0.85714285714285;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
_BRANCH_ = -1;
_ARBFMT_12 = PUT( conditional_on_price , BEST.);
%DMNORMIP( _ARBFMT_12);
IF _ARBFMT_12 IN ('12' ,'41' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_12 IN ('2' ,'1' ) THEN DO;
_BRANCH_ = 2;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Carrozzeria ) THEN DO;
_ARBFMT_23 = PUT( Carrozzeria , $23.);
%DMNORMIP( _ARBFMT_23);
IF _ARBFMT_23 IN ('CITY CAR' ,'BERLINA' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_23 IN ('ALTRO' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 AND NOT MISSING(Alimentazione ) THEN DO;
_ARBFMT_17 = PUT( Alimentazione , $17.);
%DMNORMIP( _ARBFMT_17);
IF _ARBFMT_17 IN ('METANO' ) THEN DO;
_BRANCH_ = 1;
END;
ELSE IF _ARBFMT_17 IN ('BENZINA' ,'DIESEL' ,'GPL' ) THEN DO;
_BRANCH_ = 2;
END;
END;
IF _BRANCH_ LT 0 THEN _BRANCH_ = 2;
IF _BRANCH_ EQ 1 THEN DO;
P_REP_Tipo_di_vernicBase = 0.3125;
P_REP_Tipo_di_vernicMetallizzato = 0.6875;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.3125;
Q_REP_Tipo_di_vernicMetallizzato = 0.6875;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'METALLIZZATO';
U_REP_Tipo_di_vernice = 'Metallizzato';
END;
ELSE DO;
P_REP_Tipo_di_vernicBase = 0.97058823529411;
P_REP_Tipo_di_vernicMetallizzato = 0.02941176470588;
P_REP_Tipo_di_vernicPerlato = 0;
Q_REP_Tipo_di_vernicBase = 0.97058823529411;
Q_REP_Tipo_di_vernicMetallizzato = 0.02941176470588;
Q_REP_Tipo_di_vernicPerlato = 0;
I_REP_Tipo_di_vernice = 'BASE';
U_REP_Tipo_di_vernice = 'Base';
END;
END;
END;
END;
****************************************************************;
****** END OF DECISION TREE SCORING CODE ******;
****************************************************************;
*;
* ASSIGN VALUE TO: REP_Tipo_di_vernice;
*;
length _format200 $200;
drop _format200;
_format200 = strip(I_REP_Tipo_di_vernice);
if _format200="PERLATO" then IMP_REP_Tipo_di_vernice = "Perlato     ";
else
if _format200="METALLIZZATO" then IMP_REP_Tipo_di_vernice = "Metallizzato";
else
if _format200="BASE" then IMP_REP_Tipo_di_vernice = "Base        ";
END;
